const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>$('#loader').classList.add('done'),900));
const nav=$('#nav'); window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>60),{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.14}); $$('.reveal').forEach(el=>io.observe(el));
// ambient pointer response
window.addEventListener('pointermove',e=>{const x=e.clientX/innerWidth-.5,y=e.clientY/innerHeight-.5; document.documentElement.style.setProperty('--mx',x);document.documentElement.style.setProperty('--my',y); $$('.ambient').forEach((el,i)=>el.style.transform=`translate(${x*(i+1)*20}px,${y*(i+1)*20}px)`)},{passive:true});
// particle field
const p=$('#particles'); for(let i=0;i<55;i++){const s=document.createElement('span');s.style.cssText=`position:absolute;width:${1+Math.random()*2}px;height:${1+Math.random()*2}px;border-radius:50%;background:rgba(255,255,255,${.12+Math.random()*.5});left:${Math.random()*100}%;top:${Math.random()*100}%;animation:particle ${8+Math.random()*14}s ${-Math.random()*14}s linear infinite;`;p.appendChild(s)}
const style=document.createElement('style');style.textContent='@keyframes particle{0%{transform:translate3d(0,0,0);opacity:0}15%{opacity:1}50%{transform:translate3d(calc((var(--mx,0))*80px),-70px,0)}85%{opacity:1}100%{transform:translate3d(calc((var(--mx,0))*-100px),-150px,0);opacity:0}}';document.head.appendChild(style);
// magnetic buttons
$$('.magnetic').forEach(b=>{b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});b.addEventListener('pointerleave',()=>b.style.transform='')});
// world nodes
const panel=$('#worldPanel'); const data={academics:['ACADEMICS','Nursery, KG, Primary and Junior High School — a journey designed to build strong foundations.'],life:['SCHOOL LIFE','Sports, clubs, events, culture and student activities create a campus that stays in motion.'],character:['CHARACTER','Values, discipline and personal development turn knowledge into confidence and responsibility.'],service:['SERVICE','Community, responsibility and contribution connect learning to the world beyond AIS.']};$$('.world-node').forEach(n=>n.addEventListener('click',()=>{ $$('.world-node').forEach(x=>x.classList.remove('active'));n.classList.add('active');const d=data[n.dataset.panel];panel.innerHTML=`<div class="panel-kicker">AIS WORLD / ${n.querySelector('strong').textContent}</div><h3>${d[0]}</h3><p>${d[1]}</p>`}));
// journey
const items=$$('.journey-item'), img=$('#journeyImage'), jt=$('#journeyText'), prog=$('.journey-progress span');function setJourney(i){items.forEach(x=>x.classList.remove('active'));items[i].classList.add('active');img.style.opacity=.2;img.style.transform='scale(1.05)';setTimeout(()=>{img.src=items[i].dataset.img;jt.textContent=items[i].dataset.text;img.style.opacity=1;img.style.transform='scale(1)'},180);prog.style.width=((i)/(items.length-1))*100+'%'}items.forEach((x,i)=>x.addEventListener('click',()=>setJourney(i)));
// campus drag + zoom
const view=$('#campusView'), ci=$('#campusImage');let scale=1,dx=0,dy=0,drag=false,sx=0,sy=0,ox=0,oy=0;function render(){ci.style.transform=`translate(${dx}px,${dy}px) scale(${scale})`};view.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;sy=e.clientY;ox=dx;oy=dy;view.setPointerCapture(e.pointerId)});view.addEventListener('pointermove',e=>{if(!drag)return;dx=ox+(e.clientX-sx);dy=oy+(e.clientY-sy);render()});view.addEventListener('pointerup',()=>drag=false);view.addEventListener('pointercancel',()=>drag=false);$('#zoomIn').onclick=()=>{scale=Math.min(2.2,scale+.15);render()};$('#zoomOut').onclick=()=>{scale=Math.max(1,scale-.15);render()};$('#resetView').onclick=()=>{scale=1;dx=0;dy=0;render()};
// depth cards
window.addEventListener('scroll',()=>{const sy=scrollY;$$('[data-parallax]').forEach(el=>el.style.transform=`translateY(${sy*parseFloat(el.dataset.parallax)*.08}px)`);$$('[data-depth]').forEach(el=>{const r=el.getBoundingClientRect();const d=parseFloat(el.dataset.depth);if(r.top<innerHeight&&r.bottom>0)el.querySelector('img').style.transform=`scale(1.04) translateY(${(r.top-innerHeight/2)*d}px)`})},{passive:true});
// menu
const menu=$('.menu');menu?.addEventListener('click',()=>{document.body.classList.toggle('menu-open');let m=$('.mobile-menu');if(!m){m=document.createElement('div');m.className='mobile-menu';m.innerHTML=`<a href="#about">About</a><a href="#world">Academics</a><a href="#life">School Life</a><a href="#admissions">Admissions</a><a href="#stories">Stories</a><a href="#admissions">Apply 2026/27</a>`;document.body.appendChild(m);requestAnimationFrame(()=>m.classList.add('open'));$$('.mobile-menu a').forEach(a=>a.onclick=()=>m.classList.remove('open'))}else m.classList.toggle('open')});
